name: Build base image

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ops/ToolBaseContainer/Dockerfile --tag zeroash/pal-save-tools-base:latest

    - name: Login to registry
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_KEY}}

    - name: Push the Docker image
      run: docker push zeroash/pal-save-tools-base:latest
