name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file PalworldToolset/Dockerfile --tag zeroash/palworld-toolset:latest

    - name: Login to registry
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_KEY}}

    - name: Push the Docker image
      run: docker push zeroash/palworld-toolset:latest
